include ../order.Makefile
CUSTOM_ORDER=jquery-plugins/jquery-hoverintent.js jquery-plugins/jqsimple-class.min.js jquery-plugins/jquery.json.js jquery-plugins/jquery.tipsy.js jquery-plugins/jquery.ui.autocomplete.selectFirst.js jquery-plugins/chosen.jquery.js jquery-plugins/pubsub.js lodash/lodash.js stacktrace.js
